// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxigelhprjmequkckqnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4aWdlbGhwcmptZXF1a2NrcW5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MDIxNzksImV4cCI6MjA3MDM3ODE3OX0.dJ3OQQSRei3f7uX9bS3RR3P-gjpzKIFmuqnmlXszpVY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});